#!/usr/bin/env python

#Script to use the IKA RCT Digital Hotplate and Stirrer with ROS

import rospy
from ika_rct_digital import IKADriverROS
            
if __name__ == "__main__": #Object oriented initialization for ROS
    rospy.init_node("IKA_driver", anonymous=True) #initialize rospy node
    IKA_ROS = IKADriverROS() #Create instance of ROS Wrapper
    rospy.on_shutdown(IKA_ROS.stopHeat) 
    rospy.on_shutdown(IKA_ROS.stopStir)#Turn off heater and stirrer when driver is turned off
    rospy.spin()
